# Generated by Django 3.0.5 on 2020-04-06 18:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('alias', models.TextField(max_length=30)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None)),
            ],
        ),
    ]
