# Generated by Django 3.0.5 on 2020-04-06 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0002_remove_mangas_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangas',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='mangas',
            name='hits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mangas',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mangas',
            name='title',
            field=models.TextField(null=True),
        ),
    ]
