# Generated by Django 3.0.5 on 2020-04-06 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0004_auto_20200407_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangas',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mangas',
            name='last_updated',
            field=models.IntegerField(default=1234234),
            preserve_default=False,
        ),
    ]
