# Generated by Django 3.0.5 on 2020-04-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0006_auto_20200407_0041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangas',
            options={'ordering': ['-hits']},
        ),
        migrations.AlterField(
            model_name='mangas',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Suspended'), (1, 'Ongoing'), (2, 'Completed')]),
        ),
    ]
