# Generated by Django 3.0.5 on 2020-04-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0007_auto_20200411_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangas',
            name='status',
            field=models.SmallIntegerField(choices=[(None, '(Unknown)'), (0, 'Suspended'), (1, 'Ongoing'), (2, 'Completed')]),
        ),
    ]
