# Generated by Django 3.0.5 on 2020-07-02 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0010_auto_20200412_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangas',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('hits', models.TextField(null=True)),
                ('status', models.TextField(choices=[(None, '(Unknown)'), ('ongoing', 'Ongoing'), ('completed', 'Completed')])),
                ('title', models.TextField(null=True)),
                ('last_updated', models.IntegerField(null=True)),
                ('image', models.TextField(null=True)),
                ('link', models.TextField(null=True)),
                ('ratings', models.FloatField(null=True)),
            ],
            options={
                'ordering': ['-hits'],
            },
        ),
    ]
