# Generated by Django 3.0.5 on 2020-07-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0011_mangas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapters',
            name='index',
        ),
        migrations.RemoveField(
            model_name='mangainfo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mangainfo',
            name='released',
        ),
        migrations.RemoveField(
            model_name='mangainfo',
            name='startsWith',
        ),
    ]
