# Generated by Django 3.0.5 on 2020-07-02 19:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangas', '0012_auto_20200703_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangainfo',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None),
        ),
    ]
