# Generated by Django 3.0.5 on 2020-08-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangas", "0014_auto_20200704_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="mangas",
            name="image_height",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="mangas", name="image_width", field=models.FloatField(null=True),
        ),
    ]
